version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=wcwwweecw123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=moviefinder

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./client:/client

    depends_on:
      - backend

  backend: 
    build: 
      context: ./server/backend/
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=wcwwweecw123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=moviefinder

    ports:
      - '8000:8000'

    volumes:
      - ./server:/server/backend

    depends_on:
      - db