# Generated by Django 4.2.7 on 2023-12-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("password", models.TextField()),
                ("email", models.TextField()),
                ("dob", models.TextField()),
            ],
        ),
    ]
